# Generated by Django 5.0.3 on 2024-04-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_alter_customer_options_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
