# Generated by Django 5.0.3 on 2024-04-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_employee_name_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
