# Generated by Django 5.0.3 on 2024-04-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_remove_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('developer', 'Desarrollador'), ('marketing', 'Marketing')], max_length=13, null=True),
        ),
    ]
