# Generated by Django 5.0.3 on 2024-05-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0006_alter_employee_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='state',
            new_name='status',
        ),
    ]
