# Generated by Django 5.0.3 on 2024-05-04 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0007_rename_state_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='bill',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core_api.bill'),
        ),
    ]
