# Generated by Django 5.0.3 on 2024-04-05 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(choices=[('estimating', 'Estimando'), ('paid', 'Pagado'), ('partially_paid', 'Parcialmente Pagado'), ('not_paid', 'Sin pagar')], default='estimating', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('cc', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField(verbose_name='Fecha de entrada')),
                ('date_out', models.DateTimeField(verbose_name='Fecha de finalización')),
                ('date_start', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('state', models.CharField(choices=[('planning', 'Planeando'), ('developing', 'En Desarrollo'), ('maintaining', 'En mantenimiento'), ('finished', 'Finalizado'), ('abandoned', 'Abandonado')], default='planning', max_length=11, verbose_name='Estado')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.bill')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.customer')),
                ('developer', models.ManyToManyField(related_name='assigned_processes', to='core_api.developer')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.developer')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.process')),
            ],
        ),
        migrations.AddField(
            model_name='developer',
            name='process',
            field=models.ManyToManyField(related_name='developers', through='core_api.ProcessAssignment', to='core_api.process'),
        ),
    ]
