# Generated by Django 5.0.3 on 2024-04-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': 'Process', 'verbose_name_plural': 'Processes'},
        ),
        migrations.AlterField(
            model_name='process',
            name='date_out',
            field=models.DateTimeField(blank=True, verbose_name='Fecha de finalización'),
        ),
    ]
